# Generated by Django 3.2 on 2021-07-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('school', models.CharField(max_length=50, verbose_name='school')),
                ('degree', models.CharField(max_length=50, verbose_name='degree')),
                ('univercity', models.CharField(max_length=50, verbose_name='univercity')),
                ('skill', models.TextField(verbose_name='skill')),
                ('about', models.TextField(verbose_name='about')),
                ('previous_work', models.TextField(verbose_name='previous_work')),
                ('acherviment', models.TextField(verbose_name='acherviment')),
            ],
        ),
    ]
