# Generated by Django 3.2 on 2021-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=500, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acherviment',
            field=models.TextField(max_length=1000, verbose_name='acherviment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(max_length=1000, verbose_name='previous_work'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.TextField(max_length=100, verbose_name='skill'),
        ),
    ]
