# Generated by Django 3.2 on 2021-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0002_auto_20210728_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default='', verbose_name='DOB'),
        ),
    ]
