# Generated by Django 3.2 on 2021-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0003_auto_20210728_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(verbose_name='DOB'),
        ),
    ]
