# Generated by Django 3.2 on 2021-07-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0006_remove_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='univercity',
        ),
    ]
