# Generated by Django 3.2 on 2021-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0007_remove_profile_univercity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=500, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acherviment',
            field=models.TextField(default='', max_length=1000, verbose_name='acherviment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='', max_length=50, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(default='', max_length=1000, verbose_name='previous_work'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(default='', max_length=50, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.TextField(default='', max_length=100, verbose_name='skill'),
        ),
    ]
