# Generated by Django 3.2 on 2021-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0008_auto_20210729_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=1000, verbose_name='password'),
        ),
    ]
