# Generated by Django 3.2 on 2021-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0009_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default='', verbose_name='DOB'),
        ),
    ]
