# Generated by Django 3.2 on 2021-07-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0010_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(null=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acherviment',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='acherviment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='previous_work'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.TextField(default='', max_length=100, null=True, verbose_name='skill'),
        ),
    ]
