# Generated by Django 3.2 on 2021-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0011_auto_20210729_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DOB',
        ),
        migrations.AddField(
            model_name='profile',
            name='%Y-%m-%d',
            field=models.DateField(null=True, verbose_name='new_date'),
        ),
    ]
