# Generated by Django 3.2 on 2021-07-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0017_alter_profile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_work',
        ),
    ]
