# Generated by Django 3.2 on 2021-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0019_auto_20210731_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CGPA',
            field=models.CharField(default='', max_length=500, verbose_name='CGPA'),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='', max_length=500, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='high',
            field=models.CharField(default='', max_length=500, verbose_name='high'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sec',
            field=models.CharField(default='', max_length=500, verbose_name='sec'),
        ),
    ]
