# Generated by Django 3.2 on 2021-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0020_auto_20210731_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(default='', max_length=500, verbose_name='link'),
        ),
    ]
