# Generated by Django 3.2 on 2021-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makebot', '0021_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coding',
            field=models.CharField(default='', max_length=500, verbose_name='coding'),
        ),
    ]
